# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0002_auto_20160727_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='favorite_percentage',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='favorite percentage'),
        ),
    ]
